name: BlackFlag
version: 1.0.1
author: Frivec
main: fr.frivec.BlackFlag
api-version: 1.15
website: https://twitter.com/Frivec_
depend: [AdvancedBan]
commands:
  dev:
    description: Dev Command
  setjail:
    description: Set a new jail
  removejail:
    description: Remove an existant jail
  jail:
    description: Teleport a player into or out a jail
  casier:
    description: Open the summary of a player's sanctions.